---
- hosts: all
  become: true
  vars:
    courseName: GCP
    batchnumber: 5
  tasks:
    - name: Install http servers
      yum:   
       name: httpd
       state: present
    - name: start the service
      service:
        name: httpd
        enabled: true
        state: started
    - name: copy the HTML file
      template:
        src: index.html
        dest: /var/www/html/index.html

    